### ISSUE TITLE
Calling a Lua function from JavaScript

### ISSUE THREAD

**Issue by art0rz** [mpeterv/emlua#1]
I believe it is possible to call a function in Lua from C and get its return values. How can I do the same with emlua?

I've tried using the functions outlined [here](https://www.lua.org/pil/25.2.html) with emlua, but I am getting unexpected results.

**Comment by mpeterv** [comment]
You have to do the same thing using the bindings to Lua C API emlua provides. It should be mentioned in the readme that `lua_*` functions can be used as properties of Lua state object and `luaL_*` functions as properties of `state.aux`. Here is the example from PiL translated into js, including configuration script execution and a test call of `f`:

``` js
var emlua = require('./emlua.js');

var state = emlua.state();
state.aux.openlibs();

var script = 'function f(x, y) ' +
  'return (x^2 * math.sin(y))/(1 - x)' +
'end';

state.aux.dostring(script);

function f(x, y) {
  state.getglobal('f');
  state.pushnumber(x);
  state.pushnumber(y);

  if (state.pcall(2, 1, 0) !== 0) {
    throw('error running function `f`: ' + state.tostring(-1));
  }

  if (!state.isnumber(-1)) {
    throw('function `f` must return a number');
  }

  var z = state.tonumber(-1);
  state.pop(1);
  return z;
}

console.log(f(2, 3));
state.close();
```

Running this using node I get `-0.5644800322394689` which is consistent with native Lua. Can you post what code did you try and what results did you get?

**Comment by art0rz** [comment]
Thanks, I think I was using something other than `state.aux.dostring`.

**Comment by mpeterv** [comment]
I'm closing this for now, let me know if you have any other questions.
